// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj12PkX7YNyJXmUUzHdljKo1Gl1QBKYJc',
    appId: '1:288115532033:web:4d0f94b743db31bd2c7b00',
    messagingSenderId: '288115532033',
    projectId: 'test-28a9e',
    authDomain: 'test-28a9e.firebaseapp.com',
    storageBucket: 'test-28a9e.firebasestorage.app',
    measurementId: 'G-BGCZCMPKYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQsmyt_v4IvkH8tbimlpVv2HrkSjM2tO4',
    appId: '1:288115532033:android:fc1de1320adf7efd2c7b00',
    messagingSenderId: '288115532033',
    projectId: 'test-28a9e',
    storageBucket: 'test-28a9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEQmRokyD58T9LOZeGutiIMyl8PnaQHeg',
    appId: '1:288115532033:ios:9f9a7afaa1a50b712c7b00',
    messagingSenderId: '288115532033',
    projectId: 'test-28a9e',
    storageBucket: 'test-28a9e.firebasestorage.app',
    iosBundleId: 'com.example.fe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEQmRokyD58T9LOZeGutiIMyl8PnaQHeg',
    appId: '1:288115532033:ios:9f9a7afaa1a50b712c7b00',
    messagingSenderId: '288115532033',
    projectId: 'test-28a9e',
    storageBucket: 'test-28a9e.firebasestorage.app',
    iosBundleId: 'com.example.fe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj12PkX7YNyJXmUUzHdljKo1Gl1QBKYJc',
    appId: '1:288115532033:web:3bfd238aac5b2b322c7b00',
    messagingSenderId: '288115532033',
    projectId: 'test-28a9e',
    authDomain: 'test-28a9e.firebaseapp.com',
    storageBucket: 'test-28a9e.firebasestorage.app',
    measurementId: 'G-5VKRLGL3TE',
  );
}
